version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    restart: always
    environment:
      - cluster.name=opensearch
      - node.name=opensearch-01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.compression=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - plugins.security.disabled=true 
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=false
      - plugins.security.allow_default_init_securityindex=true
      - plugins.security.authcz.admin_dn=CN=kirk,OU=client,O=client,L=test, C=DE
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
     - ./config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
     - ./roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  dashboard:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opennsearch-dashboard
    restart: always
    # network_mode: host
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - OPENSEARCH_SSL_VERIFICATIONMODE=none

    volumes:
      - ./dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - 80:5601
    networks:
      - opensearch-net
    

networks:
  opensearch-net:
    driver: bridge